# This is a basic workflow to help you get started with Actions

name: "Parts Unlimited - Pipeline"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ update-net_pipeline ]
  pull_request:
    branches: [ update-net_pipeline ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
      - name: Restore dependencies
        run: dotnet restore PartsUnlimited.sln
      - name: Build
        run: dotnet build --no-restore PartsUnlimited.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal PartsUnlimited.sln
